default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: declan_development
  username: declan_dev
  password: <%= ENV["PGPASSWORD"] || "" %>

test:
  <<: *default
  database: declan_test
  username: declan_dev
  password: <%= ENV["PGPASSWORD"] || "" %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cable:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>